// Recettes de démonstration pour le site public. Générées à partir de la base fournie
// (94 fiches, quantités par personne, ustensiles, étapes détaillées).

export interface MarketingRecipe {
  slug: string;
  name: string;
  icon: string;
  image: string | null;
  category: string;
  tag: string;
  gradient: string;
  time: string;
  prepMinutes: number;
  cookMinutes: number;
  servings: number;
  difficulty: "Facile" | "Moyen";
  desc: string;
  ingredients: string[];
  steps: string[];
  utensils: string[];
}

export const CATEGORIES = ["Rapide", "Viande", "Poisson", "Pâtes", "Riz", "Végétarien", "Salade", "Soupe", "Gratin", "Tarte", "Apéritif", "Petit déjeuner", "Dessert"] as const;

/** Ustensiles toujours supposés disponibles : jamais filtrés. */
export const BASIC_UTENSILS = ["couteau", "planche à découper", "saladier", "papier cuisson", "fouet"];

/** Équipements filtrables (correspondent aux valeurs du champ `utensils` des recettes). */
export const EQUIPMENT: { key: string; label: string; icon: string }[] = [
  { key: "four", label: "Four", icon: "🔥" },
  { key: "poêle", label: "Poêle", icon: "🍳" },
  { key: "casserole", label: "Casserole", icon: "🍲" },
  { key: "air fryer (alternative)", label: "Air fryer", icon: "🌀" },
  { key: "mixeur", label: "Mixeur / blender", icon: "🥤" },
  { key: "plat ou moule adapté", label: "Plat ou moule", icon: "🧁" },
  { key: "micro-ondes", label: "Micro-ondes", icon: "📻" },
];

export const RECIPES: MarketingRecipe[] = [
  {
    slug: "poulet-basquaise",
    name: "Poulet basquaise",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "45 min",
    gradient: "from-rose-200 to-orange-200",
    time: "45 min",
    prepMinutes: 10,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 45 min.`,
    ingredients: ["4 cuisses de poulet", "3 poivrons", "2 oignons", "400 g tomates concassées", "200 g riz", "2 gousses d'ail", "2 c. à soupe huile d'olive", "1 c. à café paprika", "1 c. à café thym"],
    steps: [`Émincer poivrons et oignons, hacher l'ail.`, `Dorer le poulet dans l'huile puis réserver.`, `Faire revenir les légumes 5 minutes; ajouter tomates et épices.`, `Remettre le poulet et mijoter 25 minutes à couvert jusqu'à cuisson complète.`, `Cuire le riz séparément selon le paquet et servir.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "chili-sin-carne",
    name: "Chili sin carne",
    icon: "🌶️",
    image: null,
    category: "Végétarien",
    tag: "35 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "35 min",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 35 min.`,
    ingredients: ["500 g haricots rouges égouttés", "280 g maïs égoutté", "800 g tomates concassées", "1 poivron rouge", "1 oignon", "2 c. à café cumin", "1 c. à café paprika", "1 c. à soupe huile d'olive"],
    steps: [`Émincer oignon et poivron.`, `Faire revenir les légumes dans l'huile 5 minutes.`, `Ajouter cumin, paprika et tomates; mijoter 10 minutes.`, `Ajouter haricots rincés et maïs égoutté puis mijoter 15 minutes.`, `Servir chaud, éventuellement avec du riz préparé à part.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "pates-tomate-basilic",
    name: "Pâtes tomate basilic",
    icon: "🍝",
    image: null,
    category: "Pâtes",
    tag: "25 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 25 min.`,
    ingredients: ["320 g pâtes", "600 g tomates concassées", "2 gousses d'ail", "1 oignon", "2 c. à soupe huile d'olive", "15 g basilic frais", "40 g parmesan"],
    steps: [`Émincer oignon et ail.`, `Faire revenir dans l'huile 3 minutes puis mijoter les tomates 12 minutes.`, `Cuire les pâtes selon le paquet et réserver un peu d'eau de cuisson.`, `Mélanger pâtes et sauce avec l'eau de cuisson; finir avec basilic et parmesan.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "spaghetti-carbonara",
    name: "Spaghetti carbonara",
    icon: "🍝",
    image: null,
    category: "Pâtes",
    tag: "22 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "22 min",
    prepMinutes: 10,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 22 min.`,
    ingredients: ["320 g spaghetti", "150 g guanciale", "3 jaunes d'œufs", "1 œuf", "80 g pecorino râpé", "1 c. à café poivre noir"],
    steps: [`Cuire les spaghetti selon le paquet en gardant une tasse d'eau de cuisson.`, `Dorer le guanciale coupé en morceaux dans une poêle sans huile.`, `Fouetter œufs, pecorino et poivre.`, `Hors du feu, mêler spaghetti et guanciale puis incorporer les œufs avec un peu d'eau de cuisson sans les faire coaguler.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet"],
  },
  {
    slug: "pates-pesto-courgettes",
    name: "Pâtes pesto courgettes",
    icon: "🍝",
    image: null,
    category: "Pâtes",
    tag: "25 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 25 min.`,
    ingredients: ["320 g pâtes", "2 courgettes", "100 g pesto", "30 g parmesan", "1 c. à soupe huile d'olive"],
    steps: [`Couper les courgettes en demi-rondelles.`, `Cuire les pâtes selon le paquet et réserver un peu d'eau de cuisson.`, `Faire dorer les courgettes dans l'huile pendant 10 minutes.`, `Mélanger les pâtes avec courgettes, pesto et un trait d'eau de cuisson; ajouter le parmesan.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "pates-au-thon-et-a-la-tomate",
    name: "Pâtes au thon et à la tomate",
    icon: "🐟",
    image: null,
    category: "Pâtes",
    tag: "26 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "26 min",
    prepMinutes: 8,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 26 min.`,
    ingredients: ["320 g pâtes", "280 g thon au naturel égoutté", "500 g tomates concassées", "1 oignon", "1 c. à soupe huile d'olive", "40 g olives noires"],
    steps: [`Cuire les pâtes selon le paquet.`, `Émincer l'oignon et le faire revenir dans l'huile 3 minutes.`, `Ajouter tomates et olives puis mijoter 10 minutes.`, `Émietter le thon dans la sauce, réchauffer 2 minutes et mélanger aux pâtes.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "pates-cremeuses-aux-champignons",
    name: "Pâtes crémeuses aux champignons",
    icon: "🍝",
    image: null,
    category: "Pâtes",
    tag: "25 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 25 min.`,
    ingredients: ["320 g pâtes", "400 g champignons de Paris", "200 ml crème liquide", "2 gousses d'ail", "1 c. à soupe huile d'olive", "30 g parmesan"],
    steps: [`Émincer champignons et ail.`, `Cuire les pâtes selon le paquet.`, `Faire sauter les champignons dans l'huile jusqu'à évaporation de leur eau; ajouter l'ail.`, `Verser la crème, épaissir 3 minutes puis mélanger aux pâtes avec le parmesan.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "one-pot-pasta-epinards-tomates",
    name: "One pot pasta épinards tomates",
    icon: "🍝",
    image: null,
    category: "Pâtes",
    tag: "25 min",
    gradient: "from-amber-200 to-yellow-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Pâtes · prêt en 25 min.`,
    ingredients: ["320 g pâtes courtes", "250 g tomates cerises", "150 g épinards frais", "1 oignon", "700 ml eau", "2 c. à soupe huile d'olive", "40 g parmesan"],
    steps: [`Couper tomates et oignon.`, `Mettre pâtes, tomates, oignon, huile et eau dans une grande casserole.`, `Porter à ébullition et cuire en remuant souvent selon le temps du paquet, en ajoutant de l'eau si besoin.`, `Incorporer les épinards 2 minutes avant la fin puis servir avec le parmesan.`],
    utensils: ["couteau", "planche à découper", "casserole"],
  },
  {
    slug: "lasagnes-bolognaise-faciles",
    name: "Lasagnes bolognaise faciles",
    icon: "🍝",
    image: null,
    category: "Gratin",
    tag: "60 min",
    gradient: "from-orange-200 to-amber-200",
    time: "60 min",
    prepMinutes: 20,
    cookMinutes: 40,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 60 min.`,
    ingredients: ["250 g feuilles de lasagne", "400 g bœuf haché", "600 g tomates concassées", "1 oignon", "500 ml béchamel", "100 g fromage râpé", "1 c. à soupe huile d'olive"],
    steps: [`Préchauffer le four à 190 °C et émincer l'oignon.`, `Faire revenir oignon et bœuf dans l'huile, puis ajouter les tomates et mijoter 15 minutes.`, `Alterner sauce, feuilles de lasagne et béchamel dans un plat; terminer par le fromage.`, `Cuire environ 25 minutes au four jusqu'à cuisson des pâtes puis laisser reposer 5 minutes.`],
    utensils: ["couteau", "planche à découper", "four", "poêle", "casserole", "plat ou moule adapté"],
  },
  {
    slug: "lasagnes-epinards-ricotta",
    name: "Lasagnes épinards ricotta",
    icon: "🍝",
    image: null,
    category: "Gratin",
    tag: "55 min",
    gradient: "from-orange-200 to-amber-200",
    time: "55 min",
    prepMinutes: 20,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 55 min.`,
    ingredients: ["250 g feuilles de lasagne", "500 g épinards", "250 g ricotta", "500 g coulis de tomate", "100 g mozzarella", "1 gousse d'ail"],
    steps: [`Préchauffer le four à 190 °C.`, `Faire tomber les épinards avec l'ail, puis mélanger à la ricotta.`, `Dans un plat, alterner coulis, pâtes et farce aux épinards.`, `Finir par la mozzarella et cuire 30 à 35 minutes jusqu'à cuisson des feuilles.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "risotto-aux-champignons",
    name: "Risotto aux champignons",
    icon: "🍚",
    image: null,
    category: "Riz",
    tag: "35 min",
    gradient: "from-yellow-200 to-lime-200",
    time: "35 min",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Riz · prêt en 35 min.`,
    ingredients: ["320 g riz arborio", "400 g champignons", "1 oignon", "1000 ml bouillon de légumes", "60 g parmesan", "20 g beurre", "1 c. à soupe huile d'olive"],
    steps: [`Chauffer le bouillon; émincer oignon et champignons.`, `Sauter les champignons dans l'huile et les réserver; faire suer l'oignon.`, `Ajouter le riz et verser le bouillon chaud louche par louche en remuant environ 18 minutes.`, `Incorporer champignons, beurre et parmesan hors du feu; servir immédiatement.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "riz-saute-aux-oeufs-et-petits-pois",
    name: "Riz sauté aux œufs et petits pois",
    icon: "🥚",
    image: null,
    category: "Riz",
    tag: "20 min",
    gradient: "from-yellow-200 to-lime-200",
    time: "20 min",
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Riz · prêt en 20 min.`,
    ingredients: ["600 g riz cuit refroidi", "3 œufs", "200 g petits pois", "2 oignons nouveaux", "2 c. à soupe sauce soja", "1 c. à soupe huile neutre"],
    steps: [`Battre les œufs et émincer les oignons nouveaux.`, `Cuire les œufs brouillés dans la poêle huilée et réserver.`, `Sauter riz et petits pois 5 minutes en séparant les grains.`, `Ajouter œufs, oignons et sauce soja; mélanger 2 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet"],
  },
  {
    slug: "riz-aux-poivrons-et-tomates",
    name: "Riz aux poivrons et tomates",
    icon: "🍚",
    image: null,
    category: "Riz",
    tag: "30 min",
    gradient: "from-yellow-200 to-lime-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Riz · prêt en 30 min.`,
    ingredients: ["280 g riz cru", "2 poivrons", "400 g tomates concassées", "1 oignon", "400 ml bouillon de légumes", "1 c. à soupe huile d'olive"],
    steps: [`Émincer l'oignon et couper les poivrons en dés.`, `Faire revenir les légumes dans l'huile 5 minutes.`, `Ajouter le riz, les tomates et le bouillon.`, `Couvrir et cuire à feu doux 15 à 18 minutes jusqu'à absorption; vérifier la tendreté du riz.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "dahl-de-lentilles-corail",
    name: "Dahl de lentilles corail",
    icon: "🍛",
    image: null,
    category: "Végétarien",
    tag: "30 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 30 min.`,
    ingredients: ["300 g lentilles corail", "400 g tomates concassées", "400 ml lait de coco", "1 oignon", "2 c. à café curry", "1 c. à soupe huile neutre", "300 ml eau"],
    steps: [`Rincer les lentilles et émincer l'oignon.`, `Faire revenir l'oignon et le curry dans l'huile 3 minutes.`, `Ajouter lentilles, tomates, coco et eau.`, `Frémir 18 à 20 minutes en remuant jusqu'à tendreté.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "curry-de-pois-chiches",
    name: "Curry de pois chiches",
    icon: "🍛",
    image: null,
    category: "Végétarien",
    tag: "30 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 30 min.`,
    ingredients: ["500 g pois chiches égouttés", "400 g tomates concassées", "200 ml lait de coco", "1 oignon", "2 c. à café curry", "1 c. à soupe huile neutre"],
    steps: [`Émincer l'oignon et rincer les pois chiches.`, `Faire revenir oignon et curry dans l'huile 4 minutes.`, `Ajouter tomates et lait de coco, puis mijoter 10 minutes.`, `Ajouter les pois chiches et cuire encore 5 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "curry-de-poulet-au-lait-de-coco",
    name: "Curry de poulet au lait de coco",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "30 min",
    gradient: "from-rose-200 to-orange-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 30 min.`,
    ingredients: ["500 g filet de poulet", "400 ml lait de coco", "1 oignon", "2 c. à café curry", "1 c. à soupe huile neutre", "240 g riz cru"],
    steps: [`Cuire le riz selon le paquet.`, `Faire revenir l'oignon et le poulet coupé en morceaux dans l'huile jusqu'à cuisson complète.`, `Ajouter le curry, puis le lait de coco.`, `Mijoter 5 minutes et servir avec le riz.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "curry-de-legumes-au-lait-de-coco",
    name: "Curry de légumes au lait de coco",
    icon: "🍛",
    image: null,
    category: "Végétarien",
    tag: "34 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "34 min",
    prepMinutes: 12,
    cookMinutes: 22,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 34 min.`,
    ingredients: ["2 carottes", "2 courgettes", "250 g pois chiches égouttés", "400 ml lait de coco", "1 oignon", "2 c. à café curry", "1 c. à soupe huile neutre"],
    steps: [`Émincer l'oignon et couper les légumes en petits dés.`, `Faire revenir oignon et carottes 5 minutes dans l'huile.`, `Ajouter courgettes, curry et coco; mijoter 12 minutes.`, `Ajouter les pois chiches et poursuivre 5 minutes jusqu'à tendreté.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "chili-con-carne-facile",
    name: "Chili con carne facile",
    icon: "🌶️",
    image: null,
    category: "Viande",
    tag: "35 min",
    gradient: "from-rose-200 to-orange-200",
    time: "35 min",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 35 min.`,
    ingredients: ["400 g bœuf haché", "500 g haricots rouges égouttés", "600 g tomates concassées", "1 oignon", "1 poivron rouge", "2 c. à café cumin", "1 c. à soupe huile neutre"],
    steps: [`Émincer l'oignon et couper le poivron en dés.`, `Faire revenir oignon et bœuf dans l'huile en émiettant la viande.`, `Ajouter poivron, cumin et tomates puis mijoter 15 minutes.`, `Ajouter les haricots rincés et cuire encore 8 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "quesadillas-fromage-haricots",
    name: "Quesadillas fromage haricots",
    icon: "🧀",
    image: null,
    category: "Rapide",
    tag: "20 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "20 min",
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 20 min.`,
    ingredients: ["8 tortillas de blé", "300 g haricots rouges égouttés", "180 g cheddar râpé", "1 poivron rouge", "1 c. à café paprika"],
    steps: [`Égoutter les haricots et couper le poivron en petits dés.`, `Répartir haricots, poivron, paprika et fromage sur la moitié des tortillas.`, `Refermer avec les les tortillas restantes.`, `Faire dorer à la poêle 3 à 4 minutes par face et découper.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "fajitas-au-poulet-et-poivrons",
    name: "Fajitas au poulet et poivrons",
    icon: "🍗",
    image: null,
    category: "Rapide",
    tag: "30 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "30 min",
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 30 min.`,
    ingredients: ["8 tortillas de blé", "500 g filet de poulet", "3 poivrons", "1 oignon", "2 c. à café paprika", "1 c. à soupe huile neutre"],
    steps: [`Couper poulet et poivrons en lanières; émincer l'oignon.`, `Cuire le poulet dans l'huile jusqu'à cuisson complète puis réserver.`, `Sauter oignon et poivrons 8 minutes, ajouter paprika et poulet.`, `Réchauffer les tortillas et les garnir.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "burritos-haricots-et-riz",
    name: "Burritos haricots et riz",
    icon: "🍚",
    image: null,
    category: "Rapide",
    tag: "30 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "30 min",
    prepMinutes: 12,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 30 min.`,
    ingredients: ["4 grandes tortillas", "200 g riz cru", "350 g haricots rouges égouttés", "200 g coulis de tomate", "100 g cheddar râpé", "1 c. à café cumin"],
    steps: [`Cuire le riz selon le paquet.`, `Réchauffer haricots et coulis avec le cumin pendant 5 minutes.`, `Répartir riz, haricots et fromage au centre des tortillas.`, `Rabattre les côtés, rouler et réchauffer 2 minutes à la poêle.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "salade-grecque",
    name: "Salade grecque",
    icon: "🥗",
    image: null,
    category: "Salade",
    tag: "15 min",
    gradient: "from-green-200 to-lime-200",
    time: "15 min",
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 15 min.`,
    ingredients: ["4 tomates", "1 concombre", "1 oignon rouge", "180 g feta", "80 g olives noires", "2 c. à soupe huile d'olive", "1 c. à café origan"],
    steps: [`Laver puis couper tomates et concombre en morceaux.`, `Émincer finement l'oignon rouge.`, `Réunir légumes et olives dans un saladier.`, `Ajouter feta en cubes, huile et origan juste avant de servir.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "salade-de-lentilles-a-la-feta",
    name: "Salade de lentilles à la feta",
    icon: "🧀",
    image: null,
    category: "Salade",
    tag: "12 min",
    gradient: "from-green-200 to-lime-200",
    time: "12 min",
    prepMinutes: 12,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 12 min.`,
    ingredients: ["500 g lentilles cuites égouttées", "2 carottes", "180 g feta", "1 oignon rouge", "2 c. à soupe huile d'olive", "1 c. à soupe jus de citron"],
    steps: [`Rincer et égoutter les lentilles.`, `Râper les carottes et émincer l'oignon.`, `Mélanger lentilles, légumes et feta émiettée.`, `Assaisonner avec huile et citron puis réserver au frais.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "salade-de-pates-tomate-mozzarella",
    name: "Salade de pâtes tomate mozzarella",
    icon: "🧀",
    image: null,
    category: "Salade",
    tag: "24 min",
    gradient: "from-green-200 to-lime-200",
    time: "24 min",
    prepMinutes: 12,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 24 min.`,
    ingredients: ["300 g pâtes courtes", "250 g tomates cerises", "200 g mozzarella", "40 g roquette", "2 c. à soupe huile d'olive", "1 c. à soupe vinaigre balsamique"],
    steps: [`Cuire les pâtes selon le paquet et les refroidir.`, `Couper tomates et mozzarella.`, `Mélanger pâtes, tomates, mozzarella et roquette.`, `Assaisonner avec huile et vinaigre au dernier moment.`],
    utensils: ["couteau", "planche à découper", "casserole", "saladier"],
  },
  {
    slug: "salade-quinoa-pois-chiches",
    name: "Salade quinoa pois chiches",
    icon: "🥗",
    image: null,
    category: "Salade",
    tag: "27 min",
    gradient: "from-green-200 to-lime-200",
    time: "27 min",
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 27 min.`,
    ingredients: ["240 g quinoa cru", "300 g pois chiches égouttés", "1 concombre", "200 g tomates cerises", "2 c. à soupe huile d'olive", "2 c. à soupe jus de citron"],
    steps: [`Rincer puis cuire le quinoa selon le paquet et le refroidir.`, `Rincer les pois chiches et couper les légumes en dés.`, `Mélanger tous les ingrédients dans un saladier.`, `Ajouter huile et citron puis mélanger de nouveau.`],
    utensils: ["couteau", "planche à découper", "casserole", "saladier"],
  },
  {
    slug: "salade-de-thon-et-oeufs",
    name: "Salade de thon et œufs",
    icon: "🐟",
    image: null,
    category: "Salade",
    tag: "32 min",
    gradient: "from-green-200 to-lime-200",
    time: "32 min",
    prepMinutes: 12,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 32 min.`,
    ingredients: ["600 g pommes de terre", "280 g thon au naturel égoutté", "4 œufs", "300 g tomates", "100 g salade verte", "2 c. à soupe huile d'olive", "1 c. à soupe vinaigre"],
    steps: [`Cuire les pommes de terre à l'eau jusqu'à tendreté.`, `Cuire les œufs 9 minutes, les refroidir puis les écaler.`, `Couper pommes de terre, tomates et œufs et les répartir sur la salade.`, `Ajouter le thon égoutté et assaisonner.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "taboule-au-boulgour",
    name: "Taboulé au boulgour",
    icon: "🥗",
    image: null,
    category: "Salade",
    tag: "27 min",
    gradient: "from-green-200 to-lime-200",
    time: "27 min",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 27 min.`,
    ingredients: ["240 g boulgour cru", "3 tomates", "1 concombre", "20 g persil frais", "20 g menthe fraîche", "3 c. à soupe jus de citron", "2 c. à soupe huile d'olive"],
    steps: [`Cuire le boulgour selon le paquet et le refroidir.`, `Couper tomates et concombre en dés; hacher les herbes.`, `Mélanger boulgour, légumes et herbes.`, `Ajouter citron et huile puis réserver 15 minutes au frais.`],
    utensils: ["couteau", "planche à découper", "casserole", "saladier"],
  },
  {
    slug: "wrap-poulet-avocat",
    name: "Wrap poulet avocat",
    icon: "🍗",
    image: null,
    category: "Rapide",
    tag: "22 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "22 min",
    prepMinutes: 12,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 22 min.`,
    ingredients: ["4 grandes tortillas", "400 g filet de poulet", "2 avocats", "100 g salade verte", "100 g yaourt nature", "1 c. à soupe jus de citron", "1 c. à soupe huile neutre"],
    steps: [`Cuire le poulet en lanières à cœur dans l'huile.`, `Écraser un avocat avec yaourt et citron et couper l'autre en lamelles.`, `Étaler la sauce sur les tortillas et ajouter salade, poulet et avocat.`, `Rouler serré et couper en deux.`],
    utensils: ["couteau", "planche à découper"],
  },
  {
    slug: "wrap-houmous-et-crudites",
    name: "Wrap houmous et crudités",
    icon: "🥙",
    image: null,
    category: "Rapide",
    tag: "12 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "12 min",
    prepMinutes: 12,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 12 min.`,
    ingredients: ["4 grandes tortillas", "200 g houmous", "2 carottes", "1 concombre", "100 g salade verte"],
    steps: [`Râper les carottes et couper le concombre en bâtonnets.`, `Étaler le houmous sur les tortillas.`, `Ajouter salade et crudités en laissant un bord libre.`, `Rabattre les côtés et rouler fermement.`],
    utensils: ["couteau", "planche à découper"],
  },
  {
    slug: "croque-monsieur-au-jambon",
    name: "Croque monsieur au jambon",
    icon: "🥪",
    image: null,
    category: "Rapide",
    tag: "18 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "18 min",
    prepMinutes: 8,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 18 min.`,
    ingredients: ["8 tranches pain de mie", "4 tranches jambon blanc", "160 g emmental râpé", "30 g beurre"],
    steps: [`Répartir jambon et fromage sur la moitié des tranches de pain.`, `Fermer avec les autres tranches et beurrer légèrement l'extérieur.`, `Faire dorer à feu moyen 4 à 5 minutes par face sous couvercle.`, `Servir quand le fromage est fondu.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "omelette-aux-champignons",
    name: "Omelette aux champignons",
    icon: "⚡",
    image: null,
    category: "Rapide",
    tag: "18 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "18 min",
    prepMinutes: 8,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 18 min.`,
    ingredients: ["8 œufs", "300 g champignons de Paris", "20 g beurre", "15 g persil frais"],
    steps: [`Émincer les champignons et hacher le persil.`, `Faire revenir les champignons dans la moitié du beurre jusqu'à évaporation de l'eau.`, `Battre les œufs puis les verser avec le reste de beurre.`, `Cuire doucement, ajouter le persil et plier l'omelette.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet"],
  },
  {
    slug: "oeufs-a-la-tomate-facon-shakshuka",
    name: "Œufs à la tomate façon shakshuka",
    icon: "🥚",
    image: null,
    category: "Rapide",
    tag: "32 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "32 min",
    prepMinutes: 12,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 32 min.`,
    ingredients: ["8 œufs", "600 g tomates concassées", "2 poivrons", "1 oignon", "1 c. à café paprika", "1 c. à soupe huile d'olive"],
    steps: [`Émincer l'oignon et couper les poivrons en dés.`, `Faire revenir dans l'huile 8 minutes puis ajouter paprika et tomates.`, `Mijoter 8 minutes et creuser un puits par œuf.`, `Casser un œuf dans chaque puits, couvrir et cuire jusqu'à ce que les blancs soient pris.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "quiche-lorraine-facile",
    name: "Quiche lorraine facile",
    icon: "🥧",
    image: null,
    category: "Tarte",
    tag: "50 min",
    gradient: "from-amber-200 to-orange-200",
    time: "50 min",
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Tarte · prêt en 50 min.`,
    ingredients: ["1 pâte brisée", "200 g lardons", "3 œufs", "250 ml crème liquide", "100 ml lait"],
    steps: [`Préchauffer le four à 180 °C et foncer un moule avec la pâte.`, `Faire dorer les lardons puis les répartir sur la pâte.`, `Battre œufs, crème et lait puis verser dans le moule.`, `Cuire 30 à 35 minutes jusqu'à prise et coloration.`],
    utensils: ["couteau", "planche à découper", "four", "poêle", "fouet", "plat ou moule adapté"],
  },
  {
    slug: "quiche-courgette-chevre",
    name: "Quiche courgette chèvre",
    icon: "🧀",
    image: null,
    category: "Tarte",
    tag: "50 min",
    gradient: "from-amber-200 to-orange-200",
    time: "50 min",
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Tarte · prêt en 50 min.`,
    ingredients: ["1 pâte brisée", "2 courgettes", "150 g fromage de chèvre", "3 œufs", "200 ml crème liquide", "1 c. à soupe huile d'olive"],
    steps: [`Préchauffer le four à 180 °C et foncer un moule.`, `Faire revenir les courgettes coupées dans l'huile jusqu'à évaporation de leur eau.`, `Battre œufs et crème, répartir courgettes et chèvre sur la pâte.`, `Verser l'appareil et cuire 30 à 35 minutes jusqu'à prise.`],
    utensils: ["couteau", "planche à découper", "four", "poêle", "fouet", "plat ou moule adapté"],
  },
  {
    slug: "tarte-tomate-moutarde",
    name: "Tarte tomate moutarde",
    icon: "🥧",
    image: null,
    category: "Tarte",
    tag: "42 min",
    gradient: "from-amber-200 to-orange-200",
    time: "42 min",
    prepMinutes: 12,
    cookMinutes: 30,
    servings: 4,
    difficulty: "Facile",
    desc: `Tarte · prêt en 42 min.`,
    ingredients: ["1 pâte feuilletée", "500 g tomates", "2 c. à soupe moutarde", "80 g emmental râpé", "1 c. à café herbes de Provence"],
    steps: [`Préchauffer le four à 190 °C et dérouler la pâte.`, `Étaler moutarde et fromage.`, `Couper les tomates en rondelles, les éponger puis les ranger sur la pâte.`, `Ajouter les herbes et cuire environ 30 minutes jusqu'à coloration.`],
    utensils: ["couteau", "planche à découper", "four"],
  },
  {
    slug: "gratin-dauphinois",
    name: "Gratin dauphinois",
    icon: "🧀",
    image: null,
    category: "Gratin",
    tag: "75 min",
    gradient: "from-orange-200 to-amber-200",
    time: "75 min",
    prepMinutes: 20,
    cookMinutes: 55,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 75 min.`,
    ingredients: ["1000 g pommes de terre", "400 ml crème liquide", "200 ml lait", "2 gousses d'ail", "10 g beurre"],
    steps: [`Préchauffer le four à 170 °C et trancher finement les pommes de terre.`, `Frotter le plat avec l'ail puis le beurrer.`, `Ranger les pommes de terre et verser crème et lait.`, `Cuire 50 à 55 minutes jusqu'à ce que les tranches soient tendres.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "gratin-de-chou-fleur",
    name: "Gratin de chou fleur",
    icon: "🧀",
    image: null,
    category: "Gratin",
    tag: "40 min",
    gradient: "from-orange-200 to-amber-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 40 min.`,
    ingredients: ["800 g chou fleur", "500 ml béchamel", "100 g emmental râpé"],
    steps: [`Préchauffer le four à 200 °C et séparer le chou fleur en bouquets.`, `Cuire les bouquets 10 minutes à l'eau puis bien les égoutter.`, `Les disposer dans un plat, couvrir de béchamel et de fromage.`, `Enfourner 15 à 20 minutes jusqu'à coloration.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "gratin-de-pates-au-jambon",
    name: "Gratin de pâtes au jambon",
    icon: "🧀",
    image: null,
    category: "Gratin",
    tag: "37 min",
    gradient: "from-orange-200 to-amber-200",
    time: "37 min",
    prepMinutes: 12,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 37 min.`,
    ingredients: ["320 g pâtes courtes", "200 g jambon blanc", "400 ml béchamel", "120 g emmental râpé"],
    steps: [`Préchauffer le four à 200 °C et cuire les pâtes deux minutes de moins que le paquet.`, `Couper le jambon en dés et mélanger aux pâtes avec la béchamel.`, `Verser dans un plat et couvrir de fromage.`, `Gratiner 15 à 20 minutes.`],
    utensils: ["couteau", "planche à découper", "four", "casserole", "plat ou moule adapté"],
  },
  {
    slug: "hachis-parmentier",
    name: "Hachis parmentier",
    icon: "🧀",
    image: null,
    category: "Gratin",
    tag: "50 min",
    gradient: "from-orange-200 to-amber-200",
    time: "50 min",
    prepMinutes: 20,
    cookMinutes: 30,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 50 min.`,
    ingredients: ["900 g pommes de terre", "400 g bœuf haché", "1 oignon", "200 ml lait", "30 g beurre", "60 g fromage râpé"],
    steps: [`Préchauffer le four à 200 °C et cuire les pommes de terre jusqu'à tendreté.`, `Les écraser avec lait et beurre pour obtenir une purée.`, `Faire revenir oignon et bœuf jusqu'à cuisson complète et étaler dans un plat.`, `Couvrir de purée et fromage puis gratiner 15 minutes.`],
    utensils: ["couteau", "planche à découper", "four", "poêle", "plat ou moule adapté"],
  },
  {
    slug: "poelee-pommes-de-terre-lardons",
    name: "Poêlée pommes de terre lardons",
    icon: "🥔",
    image: null,
    category: "Rapide",
    tag: "37 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "37 min",
    prepMinutes: 12,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 37 min.`,
    ingredients: ["800 g pommes de terre", "180 g lardons", "1 oignon", "1 c. à soupe huile neutre", "15 g persil frais"],
    steps: [`Couper les pommes de terre en petits cubes et émincer l'oignon.`, `Cuire les pommes de terre dans l'huile sous couvercle 15 minutes en remuant.`, `Ajouter oignon et lardons puis cuire 8 à 10 minutes.`, `Vérifier la tendreté et parsemer de persil.`],
    utensils: ["couteau", "planche à découper"],
  },
  {
    slug: "poelee-de-poulet-aux-courgettes",
    name: "Poêlée de poulet aux courgettes",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "28 min",
    gradient: "from-rose-200 to-orange-200",
    time: "28 min",
    prepMinutes: 10,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 28 min.`,
    ingredients: ["500 g filet de poulet", "3 courgettes", "2 gousses d'ail", "1 c. à soupe huile d'olive", "1 c. à café herbes de Provence"],
    steps: [`Couper le poulet en dés et les courgettes en demi-rondelles.`, `Dorer le poulet dans l'huile jusqu'à cuisson complète puis réserver.`, `Faire revenir courgettes et ail 8 minutes.`, `Remettre le poulet, ajouter les herbes et réchauffer 2 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "saumon-au-four-citron-herbes",
    name: "Saumon au four citron herbes",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "25 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 25 min.`,
    ingredients: ["4 pavés de saumon", "1 citron", "2 c. à soupe huile d'olive", "10 g aneth frais"],
    steps: [`Préchauffer le four à 190 °C et disposer le saumon dans un plat.`, `Arroser d'huile et de citron puis parsemer d'aneth.`, `Cuire 12 à 15 minutes selon l'épaisseur jusqu'à ce que la chair se détache facilement.`, `Servir avec le jus de cuisson.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté", "air fryer (alternative)"],
  },
  {
    slug: "cabillaud-aux-tomates-au-four",
    name: "Cabillaud aux tomates au four",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "32 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "32 min",
    prepMinutes: 12,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 32 min.`,
    ingredients: ["600 g filet de cabillaud", "500 g tomates", "1 oignon", "2 c. à soupe huile d'olive", "1 c. à café herbes de Provence"],
    steps: [`Préchauffer le four à 190 °C.`, `Disposer tomates et oignon en rondelles avec huile et herbes dans un plat.`, `Enfourner les légumes 10 minutes puis poser le cabillaud dessus.`, `Poursuivre 10 à 12 minutes jusqu'à ce que le poisson soit opaque.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "crevettes-a-l-ail-et-au-citron",
    name: "Crevettes à l'ail et au citron",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "18 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "18 min",
    prepMinutes: 10,
    cookMinutes: 8,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 18 min.`,
    ingredients: ["600 g crevettes décortiquées", "3 gousses d'ail", "1 citron", "2 c. à soupe huile d'olive", "15 g persil frais"],
    steps: [`Hacher ail et persil, presser le citron.`, `Saisir les crevettes dans l'huile 2 à 3 minutes par face.`, `Ajouter l'ail en fin de cuisson et remuer 1 minute.`, `Ajouter citron et persil hors du feu.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "poisson-en-papillote-aux-legumes",
    name: "Poisson en papillote aux légumes",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "35 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "35 min",
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 35 min.`,
    ingredients: ["600 g filets de poisson blanc", "2 courgettes", "2 carottes", "1 citron", "2 c. à soupe huile d'olive"],
    steps: [`Préchauffer le four à 190 °C et couper les légumes en fines lamelles.`, `Répartir les légumes sur une feuille de papier cuisson par personne puis poser le poisson.`, `Arroser d'huile et citron et fermer les papillotes.`, `Cuire 18 à 20 minutes et ouvrir prudemment à cause de la vapeur.`],
    utensils: ["couteau", "planche à découper", "four", "papier cuisson"],
  },
  {
    slug: "veloute-de-carottes-au-lait-de-coco",
    name: "Velouté de carottes au lait de coco",
    icon: "🍲",
    image: null,
    category: "Soupe",
    tag: "35 min",
    gradient: "from-orange-200 to-red-200",
    time: "35 min",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Soupe · prêt en 35 min.`,
    ingredients: ["800 g carottes", "1 oignon", "200 ml lait de coco", "700 ml bouillon de légumes", "1 c. à soupe huile neutre"],
    steps: [`Éplucher et couper les carottes; émincer l'oignon.`, `Faire revenir l'oignon 3 minutes puis ajouter carottes et bouillon.`, `Couvrir et cuire 20 minutes jusqu'à tendreté.`, `Ajouter le lait de coco et mixer.`],
    utensils: ["couteau", "planche à découper", "poêle", "mixeur"],
  },
  {
    slug: "soupe-de-courgettes-au-fromage-fondu",
    name: "Soupe de courgettes au fromage fondu",
    icon: "🧀",
    image: null,
    category: "Soupe",
    tag: "28 min",
    gradient: "from-orange-200 to-red-200",
    time: "28 min",
    prepMinutes: 10,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Soupe · prêt en 28 min.`,
    ingredients: ["800 g courgettes", "1 oignon", "600 ml bouillon de légumes", "4 portions fromage fondu", "1 c. à soupe huile d'olive"],
    steps: [`Couper les courgettes et émincer l'oignon.`, `Faire revenir l'oignon 3 minutes puis ajouter courgettes et bouillon.`, `Cuire 15 minutes à couvert jusqu'à tendreté.`, `Ajouter le fromage et mixer soigneusement.`],
    utensils: ["couteau", "planche à découper", "poêle", "mixeur"],
  },
  {
    slug: "minestrone-de-legumes",
    name: "Minestrone de légumes",
    icon: "🍲",
    image: null,
    category: "Soupe",
    tag: "40 min",
    gradient: "from-orange-200 to-red-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Soupe · prêt en 40 min.`,
    ingredients: ["2 carottes", "2 courgettes", "1 oignon", "400 g tomates concassées", "300 g haricots blancs égouttés", "100 g petites pâtes", "900 ml bouillon de légumes", "1 c. à soupe huile d'olive"],
    steps: [`Couper les légumes en petits dés.`, `Faire revenir oignon et carottes dans l'huile 5 minutes.`, `Ajouter courgettes, tomates et bouillon et frémir 12 minutes.`, `Ajouter pâtes et haricots puis cuire selon le temps des pâtes.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "veloute-de-potimarron",
    name: "Velouté de potimarron",
    icon: "🍲",
    image: null,
    category: "Soupe",
    tag: "40 min",
    gradient: "from-orange-200 to-red-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Soupe · prêt en 40 min.`,
    ingredients: ["800 g potimarron", "200 g pommes de terre", "1 oignon", "700 ml bouillon de légumes", "100 ml crème liquide", "1 c. à soupe huile d'olive"],
    steps: [`Retirer les graines du potimarron puis le couper; éplucher la pomme de terre.`, `Faire revenir l'oignon émincé dans l'huile.`, `Ajouter légumes et bouillon puis cuire 20 minutes.`, `Mixer avec la crème et ajuster la texture.`],
    utensils: ["couteau", "planche à découper", "poêle", "mixeur"],
  },
  {
    slug: "aubergines-a-la-parmigiana",
    name: "Aubergines à la parmigiana",
    icon: "🍆",
    image: null,
    category: "Végétarien",
    tag: "60 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "60 min",
    prepMinutes: 20,
    cookMinutes: 40,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 60 min.`,
    ingredients: ["2 aubergines", "600 g coulis de tomate", "250 g mozzarella", "50 g parmesan", "2 c. à soupe huile d'olive", "1 gousse d'ail"],
    steps: [`Préchauffer le four à 200 °C et trancher les aubergines.`, `Badigeonner d'huile et cuire les tranches 20 minutes au four.`, `Mélanger coulis et ail; alterner sauce, aubergines et mozzarella dans un plat.`, `Finir au parmesan et gratiner 15 à 20 minutes.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "ratatouille-facile",
    name: "Ratatouille facile",
    icon: "🍆",
    image: null,
    category: "Végétarien",
    tag: "55 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "55 min",
    prepMinutes: 20,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 55 min.`,
    ingredients: ["2 courgettes", "1 aubergine", "2 poivrons", "500 g tomates", "1 oignon", "2 gousses d'ail", "2 c. à soupe huile d'olive"],
    steps: [`Couper tous les légumes en dés et hacher l'ail.`, `Faire revenir oignon et poivrons 5 minutes dans l'huile.`, `Ajouter aubergine, courgettes, tomates et ail.`, `Couvrir et mijoter 30 minutes en remuant parfois.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "galettes-de-courgettes",
    name: "Galettes de courgettes",
    icon: "🥦",
    image: null,
    category: "Végétarien",
    tag: "30 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "30 min",
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 30 min.`,
    ingredients: ["3 courgettes", "2 œufs", "80 g farine", "40 g parmesan", "2 c. à soupe huile neutre"],
    steps: [`Râper les courgettes et les presser pour retirer leur eau.`, `Mélanger avec œufs, farine et parmesan.`, `Former de petites galettes dans une poêle huilée.`, `Cuire 3 à 4 minutes par face jusqu'à cuisson au centre.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "falafels-au-four",
    name: "Falafels au four",
    icon: "🧆",
    image: null,
    category: "Végétarien",
    tag: "45 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "45 min",
    prepMinutes: 20,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 45 min.`,
    ingredients: ["500 g pois chiches égouttés", "1 oignon", "2 gousses d'ail", "20 g persil frais", "2 c. à soupe farine", "1 c. à café cumin", "2 c. à soupe huile d'olive"],
    steps: [`Préchauffer le four à 200 °C et bien sécher les pois chiches.`, `Mixer grossièrement pois chiches, oignon, ail, persil, cumin et farine.`, `Former des boulettes compactes sur une plaque huilée.`, `Badigeonner d'huile et cuire environ 25 minutes en retournant à mi-cuisson.`],
    utensils: ["couteau", "planche à découper", "four", "mixeur"],
  },
  {
    slug: "burger-maison-au-boeuf",
    name: "Burger maison au bœuf",
    icon: "🥚",
    image: null,
    category: "Viande",
    tag: "27 min",
    gradient: "from-rose-200 to-orange-200",
    time: "27 min",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 27 min.`,
    ingredients: ["4 pains à burger", "500 g bœuf haché", "4 tranches cheddar", "2 tomates", "80 g salade verte", "4 c. à café moutarde", "1 c. à soupe huile neutre"],
    steps: [`Former un steak par personne avec le bœuf haché.`, `Faire cuire les steaks dans l'huile et ajouter le fromage en fin de cuisson.`, `Réchauffer les pains et couper les tomates.`, `Garnir de moutarde, salade, tomate et steak.`],
    utensils: ["couteau", "planche à découper"],
  },
  {
    slug: "burger-vegetarien-aux-haricots-rouges",
    name: "Burger végétarien aux haricots rouges",
    icon: "🍔",
    image: null,
    category: "Végétarien",
    tag: "27 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "27 min",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 27 min.`,
    ingredients: ["4 pains à burger", "400 g haricots rouges égouttés", "1 œuf", "50 g chapelure", "1 c. à café paprika", "1 c. à soupe huile neutre", "80 g salade verte"],
    steps: [`Écraser les haricots avec l'œuf, la chapelure et le paprika.`, `Former une galette par personne et laisser reposer 5 minutes.`, `Dorer les galettes dans l'huile 5 à 6 minutes de chaque côté.`, `Réchauffer les pains et garnir avec galettes et salade.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "gnocchi-sauce-tomate-mozzarella",
    name: "Gnocchi sauce tomate mozzarella",
    icon: "🧀",
    image: null,
    category: "Rapide",
    tag: "23 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "23 min",
    prepMinutes: 8,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 23 min.`,
    ingredients: ["800 g gnocchi", "500 g coulis de tomate", "150 g mozzarella", "1 gousse d'ail", "1 c. à soupe huile d'olive"],
    steps: [`Faire dorer les gnocchi dans l'huile 6 à 8 minutes.`, `Ajouter l'ail haché puis le coulis et mijoter 5 minutes.`, `Répartir la mozzarella en morceaux sur les gnocchi.`, `Couvrir 2 minutes pour faire fondre le fromage.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "gnocchi-epinards-creme",
    name: "Gnocchi épinards crème",
    icon: "🍝",
    image: null,
    category: "Rapide",
    tag: "20 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "20 min",
    prepMinutes: 8,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 20 min.`,
    ingredients: ["800 g gnocchi", "250 g épinards frais", "200 ml crème liquide", "1 gousse d'ail", "1 c. à soupe huile d'olive", "40 g parmesan"],
    steps: [`Poêler les gnocchi dans l'huile jusqu'à coloration.`, `Ajouter ail et épinards puis laisser tomber ces derniers.`, `Verser la crème et frémir 3 minutes.`, `Ajouter le parmesan et servir.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "couscous-de-legumes-express",
    name: "Couscous de légumes express",
    icon: "🥦",
    image: null,
    category: "Végétarien",
    tag: "35 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "35 min",
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 35 min.`,
    ingredients: ["280 g semoule de couscous", "2 carottes", "2 courgettes", "300 g pois chiches égouttés", "500 ml bouillon de légumes", "2 c. à café ras el hanout", "1 c. à soupe huile d'olive"],
    steps: [`Couper les légumes en dés.`, `Faire revenir les carottes avec épices et huile 5 minutes, puis ajouter courgettes et 300 ml de bouillon.`, `Mijoter 12 minutes et ajouter les pois chiches en fin de cuisson.`, `Verser 200 ml de bouillon chaud sur la semoule, couvrir 5 minutes puis égrainer.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole", "plat ou moule adapté"],
  },
  {
    slug: "semoule-au-poulet-et-legumes",
    name: "Semoule au poulet et légumes",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "32 min",
    gradient: "from-rose-200 to-orange-200",
    time: "32 min",
    prepMinutes: 12,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 32 min.`,
    ingredients: ["400 g filet de poulet", "280 g semoule de couscous", "2 carottes", "2 courgettes", "400 ml bouillon de légumes", "1 c. à soupe huile d'olive", "1 c. à café cumin"],
    steps: [`Couper le poulet en dés et les légumes en petits morceaux.`, `Cuire le poulet dans l'huile jusqu'à cuisson complète puis ajouter légumes et cumin.`, `Verser 200 ml de bouillon et mijoter 10 minutes jusqu'à tendreté.`, `Verser le bouillon restant chaud sur la semoule, couvrir 5 minutes et égrainer.`],
    utensils: ["couteau", "planche à découper", "casserole", "plat ou moule adapté"],
  },
  {
    slug: "nouilles-sautees-aux-legumes",
    name: "Nouilles sautées aux légumes",
    icon: "🥢",
    image: null,
    category: "Rapide",
    tag: "24 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "24 min",
    prepMinutes: 12,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 24 min.`,
    ingredients: ["300 g nouilles de blé", "2 carottes", "1 poivron rouge", "1 courgette", "3 c. à soupe sauce soja", "1 c. à soupe huile neutre"],
    steps: [`Cuire les nouilles selon le paquet et égoutter.`, `Couper les légumes en fines lanières.`, `Sauter les légumes dans l'huile 6 à 8 minutes.`, `Ajouter nouilles et sauce soja, remuer 2 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "nouilles-sautees-au-poulet",
    name: "Nouilles sautées au poulet",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "27 min",
    gradient: "from-rose-200 to-orange-200",
    time: "27 min",
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 27 min.`,
    ingredients: ["300 g nouilles de blé", "450 g filet de poulet", "2 carottes", "3 c. à soupe sauce soja", "1 c. à soupe huile neutre", "2 oignons nouveaux"],
    steps: [`Cuire les nouilles selon le paquet.`, `Couper poulet en lamelles, râper carottes et émincer oignons.`, `Sauter le poulet dans l'huile jusqu'à cuisson complète puis ajouter carottes.`, `Ajouter nouilles et sauce soja, remuer 2 minutes et finir avec les oignons.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "porridge-a-la-banane",
    name: "Porridge à la banane",
    icon: "🥣",
    image: null,
    category: "Petit déjeuner",
    tag: "13 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "13 min",
    prepMinutes: 5,
    cookMinutes: 8,
    servings: 2,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 13 min.`,
    ingredients: ["100 g flocons d'avoine", "350 ml lait", "2 bananes", "1 c. à café cannelle"],
    steps: [`Chauffer lait et flocons à feu doux.`, `Remuer 6 à 8 minutes jusqu'à épaississement.`, `Écraser une banane et l'incorporer.`, `Répartir dans un bol par personne avec la seconde banane et la cannelle.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "flocons-d-avoine-au-yaourt-et-fruits",
    name: "Flocons d'avoine au yaourt et fruits",
    icon: "🍎",
    image: null,
    category: "Petit déjeuner",
    tag: "10 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "10 min",
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 2,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 10 min.`,
    ingredients: ["100 g flocons d'avoine", "250 g yaourt nature", "150 ml lait", "150 g fruits rouges", "1 c. à soupe miel"],
    steps: [`Mélanger flocons, yaourt et lait dans un bocal par personne.`, `Ajouter le miel et remuer.`, `Fermer et réfrigérer au moins 6 heures.`, `Ajouter les fruits au moment de servir.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "pancakes-a-la-banane",
    name: "Pancakes à la banane",
    icon: "🥞",
    image: null,
    category: "Petit déjeuner",
    tag: "22 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "22 min",
    prepMinutes: 10,
    cookMinutes: 12,
    servings: 4,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 22 min.`,
    ingredients: ["2 bananes", "2 œufs", "160 g farine", "180 ml lait", "1 c. à café levure chimique", "1 c. à soupe huile neutre"],
    steps: [`Écraser les bananes et fouetter avec œufs et lait.`, `Ajouter farine et levure sans trop travailler la pâte.`, `Déposer de petites louches dans une poêle huilée chaude.`, `Cuire environ 2 minutes de chaque côté.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet", "saladier"],
  },
  {
    slug: "crepes-faciles",
    name: "Crêpes faciles",
    icon: "🥞",
    image: null,
    category: "Dessert",
    tag: "30 min",
    gradient: "from-pink-200 to-rose-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Dessert · prêt en 30 min.`,
    ingredients: ["250 g farine", "3 œufs", "500 ml lait", "20 g beurre fondu"],
    steps: [`Verser la farine dans un saladier et creuser un puits.`, `Ajouter les œufs puis incorporer progressivement le lait au fouet.`, `Ajouter le beurre fondu et laisser reposer 15 minutes si possible.`, `Cuire de fines crêpes dans une poêle légèrement beurrée.`],
    utensils: ["couteau", "planche à découper", "poêle", "saladier"],
  },
  {
    slug: "gateau-au-yaourt",
    name: "Gâteau au yaourt",
    icon: "🍫",
    image: null,
    category: "Dessert",
    tag: "47 min",
    gradient: "from-pink-200 to-rose-200",
    time: "47 min",
    prepMinutes: 12,
    cookMinutes: 35,
    servings: 8,
    difficulty: "Facile",
    desc: `Dessert · prêt en 47 min.`,
    ingredients: ["125 g yaourt nature", "375 g farine", "250 g sucre", "60 ml huile neutre", "3 œufs", "1 sachet levure chimique"],
    steps: [`Préchauffer le four à 180 °C.`, `Mélanger yaourt, œufs et sucre puis incorporer farine et levure.`, `Ajouter l'huile et mélanger jusqu'à homogénéité.`, `Verser dans un moule et cuire 30 à 35 minutes; vérifier la cuisson.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté", "saladier"],
  },
  {
    slug: "moelleux-au-chocolat",
    name: "Moelleux au chocolat",
    icon: "🍫",
    image: null,
    category: "Dessert",
    tag: "32 min",
    gradient: "from-pink-200 to-rose-200",
    time: "32 min",
    prepMinutes: 12,
    cookMinutes: 20,
    servings: 6,
    difficulty: "Facile",
    desc: `Dessert · prêt en 32 min.`,
    ingredients: ["200 g chocolat noir", "120 g beurre", "100 g sucre", "3 œufs", "60 g farine"],
    steps: [`Préchauffer le four à 180 °C et fondre chocolat et beurre doucement.`, `Fouetter œufs et sucre puis incorporer le chocolat fondu.`, `Ajouter la farine sans trop travailler.`, `Verser dans un moule et cuire 18 à 22 minutes selon son épaisseur.`],
    utensils: ["couteau", "planche à découper", "four", "fouet", "plat ou moule adapté", "saladier"],
  },
  {
    slug: "cookies-aux-pepites-de-chocolat",
    name: "Cookies aux pépites de chocolat",
    icon: "🍪",
    image: null,
    category: "Dessert",
    tag: "27 min",
    gradient: "from-pink-200 to-rose-200",
    time: "27 min",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 12,
    difficulty: "Facile",
    desc: `Dessert · prêt en 27 min.`,
    ingredients: ["150 g farine", "100 g beurre mou", "80 g sucre", "1 œuf", "100 g pépites de chocolat", "0,5 c. à café levure chimique"],
    steps: [`Préchauffer le four à 180 °C.`, `Mélanger beurre, sucre et œuf puis ajouter farine, levure et pépites.`, `Former une boule par portion espacées sur une plaque.`, `Cuire 10 à 12 minutes et laisser refroidir sur la plaque.`],
    utensils: ["couteau", "planche à découper", "four", "saladier"],
  },
  {
    slug: "compote-de-pommes-maison",
    name: "Compote de pommes maison",
    icon: "🍎",
    image: null,
    category: "Dessert",
    tag: "30 min",
    gradient: "from-pink-200 to-rose-200",
    time: "30 min",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "Facile",
    desc: `Dessert · prêt en 30 min.`,
    ingredients: ["800 g pommes", "100 ml eau", "1 c. à café cannelle"],
    steps: [`Éplucher, épépiner et couper les pommes.`, `Mettre pommes, eau et cannelle dans une casserole.`, `Couvrir et cuire à feu doux 15 à 20 minutes en remuant.`, `Écraser à la fourchette ou mixer.`],
    utensils: ["couteau", "planche à découper", "four", "casserole", "mixeur", "saladier"],
  },
  {
    slug: "salade-de-fruits-frais",
    name: "Salade de fruits frais",
    icon: "🥗",
    image: null,
    category: "Dessert",
    tag: "15 min",
    gradient: "from-pink-200 to-rose-200",
    time: "15 min",
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Dessert · prêt en 15 min.`,
    ingredients: ["2 pommes", "2 oranges", "2 kiwis", "2 bananes", "1 c. à soupe jus de citron"],
    steps: [`Laver et éplucher les fruits.`, `Couper tous les fruits en morceaux.`, `Réunir dans un saladier et arroser de jus de citron.`, `Mélanger délicatement et servir frais.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "riz-au-lait-vanille",
    name: "Riz au lait vanillé",
    icon: "🍮",
    image: null,
    category: "Dessert",
    tag: "40 min",
    gradient: "from-pink-200 to-rose-200",
    time: "40 min",
    prepMinutes: 5,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Dessert · prêt en 40 min.`,
    ingredients: ["150 g riz rond", "750 ml lait", "60 g sucre", "1 gousse de vanille"],
    steps: [`Rincer le riz et fendre la vanille.`, `Chauffer lait, vanille et sucre dans une casserole.`, `Ajouter le riz et cuire à feu très doux 30 à 35 minutes en remuant souvent.`, `Retirer la gousse et laisser tiédir.`],
    utensils: ["couteau", "planche à découper", "casserole", "saladier"],
  },
  {
    slug: "pain-perdu-a-la-banane",
    name: "Pain perdu à la banane",
    icon: "🍞",
    image: null,
    category: "Petit déjeuner",
    tag: "18 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "18 min",
    prepMinutes: 8,
    cookMinutes: 10,
    servings: 4,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 18 min.`,
    ingredients: ["8 tranches pain rassis", "2 œufs", "250 ml lait", "2 bananes", "20 g beurre", "1 c. à café cannelle"],
    steps: [`Fouetter œufs, lait et cannelle.`, `Tremper rapidement le pain dans le mélange.`, `Dorer le pain dans le beurre 2 à 3 minutes par face.`, `Ajouter les bananes en rondelles et servir.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet", "saladier"],
  },
  {
    slug: "houmous-maison",
    name: "Houmous maison",
    icon: "🥙",
    image: null,
    category: "Apéritif",
    tag: "10 min",
    gradient: "from-teal-200 to-emerald-200",
    time: "10 min",
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 6,
    difficulty: "Facile",
    desc: `Apéritif · prêt en 10 min.`,
    ingredients: ["500 g pois chiches égouttés", "50 g tahini", "3 c. à soupe jus de citron", "1 gousse d'ail", "3 c. à soupe huile d'olive", "60 ml eau"],
    steps: [`Rincer et égoutter les pois chiches.`, `Mixer avec tahini, citron, ail et huile.`, `Ajouter l'eau peu à peu en mixant jusqu'à une texture souple.`, `Goûter et ajuster le citron.`],
    utensils: ["couteau", "planche à découper", "mixeur", "saladier"],
  },
  {
    slug: "guacamole-simple",
    name: "Guacamole simple",
    icon: "🥑",
    image: null,
    category: "Apéritif",
    tag: "10 min",
    gradient: "from-teal-200 to-emerald-200",
    time: "10 min",
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Apéritif · prêt en 10 min.`,
    ingredients: ["3 avocats", "1 tomate", "0,5 oignon rouge", "2 c. à soupe jus de citron", "10 g coriandre fraîche"],
    steps: [`Écraser l'avocat avec le citron.`, `Couper tomate en dés et hacher oignon et coriandre.`, `Incorporer les légumes à l'avocat.`, `Servir rapidement.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "tzatziki-au-concombre",
    name: "Tzatziki au concombre",
    icon: "🥒",
    image: null,
    category: "Apéritif",
    tag: "12 min",
    gradient: "from-teal-200 to-emerald-200",
    time: "12 min",
    prepMinutes: 12,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Apéritif · prêt en 12 min.`,
    ingredients: ["300 g yaourt grec", "1 concombre", "1 gousse d'ail", "1 c. à soupe huile d'olive", "1 c. à soupe jus de citron", "10 g aneth frais"],
    steps: [`Râper le concombre et le presser pour retirer l'eau.`, `Mélanger yaourt, concombre, ail, huile et citron.`, `Ajouter l'aneth ciselé.`, `Réserver 15 minutes au frais.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "bruschetta-tomate-basilic",
    name: "Bruschetta tomate basilic",
    icon: "🍞",
    image: null,
    category: "Apéritif",
    tag: "17 min",
    gradient: "from-teal-200 to-emerald-200",
    time: "17 min",
    prepMinutes: 12,
    cookMinutes: 5,
    servings: 4,
    difficulty: "Facile",
    desc: `Apéritif · prêt en 17 min.`,
    ingredients: ["8 tranches pain de campagne", "400 g tomates", "2 gousses d'ail", "15 g basilic frais", "2 c. à soupe huile d'olive"],
    steps: [`Couper les tomates en petits dés et mélanger avec basilic et huile.`, `Griller les tranches de pain.`, `Frotter le pain encore chaud avec l'ail coupé.`, `Répartir les tomates juste avant de servir.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "bowl-de-quinoa-aux-legumes-rotis",
    name: "Bowl de quinoa aux légumes rôtis",
    icon: "🥦",
    image: null,
    category: "Végétarien",
    tag: "40 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 40 min.`,
    ingredients: ["240 g quinoa cru", "3 carottes", "2 courgettes", "200 g yaourt nature", "1 c. à soupe jus de citron", "2 c. à soupe huile d'olive"],
    steps: [`Préchauffer le four à 200 °C et couper les légumes.`, `Mélanger à l'huile et rôtir sur une plaque 20 à 25 minutes.`, `Cuire le quinoa selon le paquet.`, `Mélanger yaourt et citron et servir avec légumes et quinoa.`],
    utensils: ["couteau", "planche à découper", "four", "casserole"],
  },
  {
    slug: "bowl-de-saumon-cuit-et-avocat",
    name: "Bowl de saumon cuit et avocat",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "33 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "33 min",
    prepMinutes: 15,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 33 min.`,
    ingredients: ["280 g riz cru", "400 g saumon sans peau", "2 avocats", "1 concombre", "2 c. à soupe sauce soja", "1 c. à soupe huile neutre"],
    steps: [`Cuire le riz selon le paquet.`, `Cuire complètement les morceaux de saumon dans une poêle huilée.`, `Couper avocat et concombre.`, `Répartir riz, saumon et légumes dans un bol par personne; ajouter la sauce soja.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "pommes-de-terre-farcies-au-thon",
    name: "Pommes de terre farcies au thon",
    icon: "🐟",
    image: null,
    category: "Rapide",
    tag: "47 min",
    gradient: "from-fuchsia-200 to-rose-200",
    time: "47 min",
    prepMinutes: 12,
    cookMinutes: 35,
    servings: 4,
    difficulty: "Facile",
    desc: `Rapide · prêt en 47 min.`,
    ingredients: ["4 grosses pommes de terre", "280 g thon au naturel égoutté", "200 g fromage blanc", "1 oignon rouge", "1 c. à soupe jus de citron"],
    steps: [`Préchauffer le four à 200 °C, piquer les pommes de terre et cuire jusqu'à tendreté environ 35 minutes.`, `Mélanger thon, fromage blanc, oignon émincé et citron.`, `Ouvrir les pommes de terre chaudes.`, `Garnir du mélange au thon et servir.`],
    utensils: ["couteau", "planche à découper", "four"],
  },
  {
    slug: "lentilles-aux-saucisses",
    name: "Lentilles aux saucisses",
    icon: "🫘",
    image: null,
    category: "Viande",
    tag: "45 min",
    gradient: "from-rose-200 to-orange-200",
    time: "45 min",
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 45 min.`,
    ingredients: ["280 g lentilles vertes sèches", "4 saucisses", "2 carottes", "1 oignon", "900 ml eau", "1 feuille de laurier", "1 c. à soupe huile neutre"],
    steps: [`Rincer les lentilles et couper les légumes.`, `Faire revenir oignon, carottes et saucisses dans l'huile 5 minutes.`, `Ajouter lentilles, eau et laurier puis frémir 25 à 30 minutes.`, `Vérifier la tendreté des lentilles et la cuisson des saucisses.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "blanquette-de-poulet-rapide",
    name: "Blanquette de poulet rapide",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "40 min",
    gradient: "from-rose-200 to-orange-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 40 min.`,
    ingredients: ["500 g filet de poulet", "3 carottes", "250 g champignons", "1 oignon", "200 ml crème liquide", "300 ml bouillon de volaille", "1 c. à soupe huile neutre"],
    steps: [`Couper poulet et légumes.`, `Faire revenir oignon et poulet puis ajouter carottes et bouillon.`, `Couvrir et mijoter 15 minutes; ajouter champignons et cuire 8 minutes.`, `Vérifier le poulet puis incorporer la crème et réchauffer.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "boeuf-saute-au-brocoli",
    name: "Bœuf sauté au brocoli",
    icon: "🥚",
    image: null,
    category: "Viande",
    tag: "27 min",
    gradient: "from-rose-200 to-orange-200",
    time: "27 min",
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 27 min.`,
    ingredients: ["450 g bœuf à émincer", "500 g brocoli", "3 c. à soupe sauce soja", "1 gousse d'ail", "1 c. à soupe huile neutre", "100 ml eau"],
    steps: [`Séparer le brocoli en bouquets et émincer le bœuf.`, `Cuire le brocoli 4 minutes à l'eau bouillante.`, `Saisir le bœuf dans l'huile puis ajouter l'ail.`, `Ajouter brocoli, eau et sauce soja et mélanger 3 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "poulet-sauce-moutarde",
    name: "Poulet sauce moutarde",
    icon: "🍗",
    image: null,
    category: "Viande",
    tag: "28 min",
    gradient: "from-rose-200 to-orange-200",
    time: "28 min",
    prepMinutes: 10,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Viande · prêt en 28 min.`,
    ingredients: ["500 g filet de poulet", "200 ml crème liquide", "2 c. à soupe moutarde", "1 oignon", "1 c. à soupe huile neutre"],
    steps: [`Couper le poulet et émincer l'oignon.`, `Faire revenir dans l'huile jusqu'à cuisson complète du poulet.`, `Mélanger crème et moutarde puis verser dans la poêle.`, `Frémir 4 minutes en remuant.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "tortilla-de-pommes-de-terre",
    name: "Tortilla de pommes de terre",
    icon: "🌮",
    image: null,
    category: "Végétarien",
    tag: "40 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "40 min",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 40 min.`,
    ingredients: ["600 g pommes de terre", "6 œufs", "1 oignon", "3 c. à soupe huile d'olive"],
    steps: [`Éplucher et trancher les pommes de terre puis émincer l'oignon.`, `Cuire pommes de terre et oignon dans l'huile sous couvercle 15 minutes.`, `Battre les œufs et y incorporer les légumes.`, `Verser dans une poêle et cuire 5 minutes par face à feu doux.`],
    utensils: ["couteau", "planche à découper", "poêle", "fouet"],
  },
  {
    slug: "riz-aux-lentilles-et-oignons",
    name: "Riz aux lentilles et oignons",
    icon: "🍚",
    image: null,
    category: "Végétarien",
    tag: "37 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "37 min",
    prepMinutes: 12,
    cookMinutes: 25,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 37 min.`,
    ingredients: ["200 g riz cru", "200 g lentilles vertes sèches", "2 oignons", "2 c. à soupe huile d'olive", "1 c. à café cumin"],
    steps: [`Cuire les lentilles rincées dans l'eau environ 20 à 25 minutes.`, `Cuire le riz séparément selon le paquet.`, `Faire dorer les oignons émincés dans l'huile 12 minutes.`, `Mélanger riz, lentilles et cumin et servir avec les oignons.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "polenta-cremeuse-aux-champignons",
    name: "Polenta crémeuse aux champignons",
    icon: "🌽",
    image: null,
    category: "Végétarien",
    tag: "25 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "25 min",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 25 min.`,
    ingredients: ["250 g polenta instantanée", "750 ml eau", "350 g champignons", "50 g parmesan", "20 g beurre", "1 c. à soupe huile d'olive"],
    steps: [`Sauter les champignons émincés dans l'huile jusqu'à coloration.`, `Porter l'eau à ébullition et verser la polenta en pluie en remuant.`, `Cuire selon le paquet et incorporer beurre et parmesan.`, `Servir avec les champignons.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "salade-de-riz-au-thon-et-mais",
    name: "Salade de riz au thon et maïs",
    icon: "🐟",
    image: null,
    category: "Salade",
    tag: "27 min",
    gradient: "from-green-200 to-lime-200",
    time: "27 min",
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 27 min.`,
    ingredients: ["280 g riz cru", "280 g thon au naturel égoutté", "250 g maïs égoutté", "300 g tomates", "2 c. à soupe huile d'olive", "1 c. à soupe jus de citron"],
    steps: [`Cuire le riz selon le paquet, refroidir et égoutter.`, `Couper les tomates et égoutter thon et maïs.`, `Mélanger dans un saladier.`, `Ajouter huile et citron puis réserver au frais.`],
    utensils: ["couteau", "planche à découper", "casserole", "saladier"],
  },
  {
    slug: "toast-avocat-et-oeuf",
    name: "Toast avocat et œuf",
    icon: "🥚",
    image: null,
    category: "Petit déjeuner",
    tag: "18 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "18 min",
    prepMinutes: 10,
    cookMinutes: 8,
    servings: 2,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 18 min.`,
    ingredients: ["4 tranches pain complet", "1 avocat", "2 œufs", "1 c. à soupe jus de citron", "1 c. à café huile d'olive"],
    steps: [`Griller le pain et écraser l'avocat avec le citron.`, `Cuire les œufs à la poêle avec l'huile.`, `Répartir l'avocat sur les toasts.`, `Déposer les œufs et servir.`],
    utensils: ["couteau", "planche à découper", "poêle", "saladier"],
  },
  {
    slug: "smoothie-banane-fruits-rouges",
    name: "Smoothie banane fruits rouges",
    icon: "🍎",
    image: null,
    category: "Petit déjeuner",
    tag: "5 min",
    gradient: "from-yellow-200 to-orange-200",
    time: "5 min",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 2,
    difficulty: "Facile",
    desc: `Petit déjeuner · prêt en 5 min.`,
    ingredients: ["2 bananes", "200 g fruits rouges", "250 g yaourt nature", "150 ml lait"],
    steps: [`Éplucher et couper les bananes.`, `Mettre tous les ingrédients dans un blender.`, `Mixer jusqu'à une consistance lisse.`, `Servir aussitôt dans un verre par personne.`],
    utensils: ["couteau", "planche à découper", "mixeur", "saladier"],
  },
  {
    slug: "salade-de-concombre-au-yaourt",
    name: "Salade de concombre au yaourt",
    icon: "🥗",
    image: null,
    category: "Salade",
    tag: "10 min",
    gradient: "from-green-200 to-lime-200",
    time: "10 min",
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 4,
    difficulty: "Facile",
    desc: `Salade · prêt en 10 min.`,
    ingredients: ["2 concombres", "200 g yaourt nature", "1 c. à soupe jus de citron", "10 g aneth frais"],
    steps: [`Couper les concombres en fines demi-rondelles.`, `Mélanger yaourt, citron et aneth.`, `Ajouter le concombre et mélanger.`, `Réserver au frais jusqu'au service.`],
    utensils: ["couteau", "planche à découper", "saladier"],
  },
  {
    slug: "poelee-haricots-verts-pommes-de-terre",
    name: "Poêlée haricots verts pommes de terre",
    icon: "🥔",
    image: null,
    category: "Végétarien",
    tag: "34 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "34 min",
    prepMinutes: 12,
    cookMinutes: 22,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 34 min.`,
    ingredients: ["500 g haricots verts", "600 g pommes de terre", "2 gousses d'ail", "2 c. à soupe huile d'olive"],
    steps: [`Couper les pommes de terre en dés et les cuire 10 minutes à l'eau.`, `Cuire les haricots verts 8 à 10 minutes puis égoutter.`, `Faire dorer pommes de terre, haricots et ail dans l'huile 5 minutes.`, `Servir dès que les légumes sont chauds et colorés.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
  {
    slug: "riz-aux-crevettes-et-courgettes",
    name: "Riz aux crevettes et courgettes",
    icon: "🐟",
    image: null,
    category: "Poisson",
    tag: "30 min",
    gradient: "from-sky-200 to-cyan-200",
    time: "30 min",
    prepMinutes: 12,
    cookMinutes: 18,
    servings: 4,
    difficulty: "Facile",
    desc: `Poisson · prêt en 30 min.`,
    ingredients: ["280 g riz cru", "500 g crevettes décortiquées", "2 courgettes", "2 gousses d'ail", "2 c. à soupe huile d'olive"],
    steps: [`Cuire le riz selon le paquet.`, `Couper les courgettes en dés et hacher l'ail.`, `Sauter les courgettes 8 minutes puis ajouter les crevettes et cuire jusqu'à opacité.`, `Ajouter ail et riz et mélanger 2 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle", "casserole"],
  },
  {
    slug: "gratin-de-brocoli-et-pommes-de-terre",
    name: "Gratin de brocoli et pommes de terre",
    icon: "🧀",
    image: null,
    category: "Gratin",
    tag: "45 min",
    gradient: "from-orange-200 to-amber-200",
    time: "45 min",
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 4,
    difficulty: "Facile",
    desc: `Gratin · prêt en 45 min.`,
    ingredients: ["500 g brocoli", "600 g pommes de terre", "400 ml béchamel", "100 g emmental râpé"],
    steps: [`Préchauffer le four à 200 °C.`, `Cuire pommes de terre en dés 10 minutes et brocoli en bouquets 5 minutes.`, `Égoutter et couvrir de béchamel et fromage dans un plat.`, `Gratiner 20 minutes jusqu'à tendreté des pommes de terre.`],
    utensils: ["couteau", "planche à découper", "four", "plat ou moule adapté"],
  },
  {
    slug: "tofu-saute-aux-legumes",
    name: "Tofu sauté aux légumes",
    icon: "🥢",
    image: null,
    category: "Végétarien",
    tag: "27 min",
    gradient: "from-emerald-200 to-lime-200",
    time: "27 min",
    prepMinutes: 12,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Facile",
    desc: `Végétarien · prêt en 27 min.`,
    ingredients: ["400 g tofu ferme", "2 carottes", "2 poivrons", "3 c. à soupe sauce soja", "1 c. à soupe huile neutre"],
    steps: [`Éponger et couper le tofu, émincer les légumes.`, `Dorer le tofu dans l'huile et réserver.`, `Sauter carottes et poivrons 8 minutes.`, `Remettre le tofu, ajouter la sauce soja et cuire 2 minutes.`],
    utensils: ["couteau", "planche à découper", "poêle"],
  },
];

export function getRecipe(slug: string) {
  return RECIPES.find((r) => r.slug === slug) ?? null;
}

/** Filtre commun (site public, onglet Trouver des recettes, sélecteur de courses). */
export function filterRecipes(list: MarketingRecipe[], { query = "", category = null, equipment = [] }: { query?: string; category?: string | null; equipment?: string[] }) {
  const q = query.trim().toLowerCase();
  return list.filter((r) => {
    if (category && r.category !== category) return false;
    if (equipment.length > 0 && r.utensils.some((u) => !BASIC_UTENSILS.includes(u) && !equipment.includes(u))) return false;
    if (!q) return true;
    return r.name.toLowerCase().includes(q) || r.desc.toLowerCase().includes(q) || r.ingredients.some((i) => i.toLowerCase().includes(q));
  });
}
